name: Build
on: [push, pull_request]
jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-20.04
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew check build --stacktrace
      - uses: actions/upload-artifact@v2
        if: "contains(toJSON(github.event.commits.*.message), '[ci upload]')"
        with:
          name: Artifacts
          path: build/libs/
